### ISSUE TITLE
vcc bool regression

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2729]
regression from 47dc5fd732eddff135d7c75672f2d3e28f324705

Ref #2727

with the following vcl (note that semantically this is complete nonsense):

```
vcl 4.1;

backend t {
	.host = "127.0.0.1";
}
sub vcl_recv {
	if (req.grace < 0s || req.grace < 1s && req.grace < 2s) {
		return (synth(200));
	}
}
```

we get:

```
Message from VCC-compiler:
Expected ')' got '&&'
(program line 68), at
('/tmp/t.vcl' Line 7 Pos 46)
        if (req.grace < 0s || req.grace < 1s && req.grace < 2s) {
---------------------------------------------##------------------

Running VCC-compiler failed, exited with 2
VCL compilation failed

```
