### ISSUE TITLE
7.0 fails to build on macos 10.15

### ISSUE THREAD

**Issue by risicle** [varnishcache/varnish-cache#3699]
Clang 7, macos 10.15:

```
http2/cache_http2_panic.c:111:7: error: format specifies type 'intmax_t' (aka 'long') but the argument has type 'int64_t' (aka 'long long') [-Werror,-Wformat]
                    r2->t_window, r2->r_window);
                    ^~~~~~~~~~~~
http2/cache_http2_panic.c:111:21: error: format specifies type 'intmax_t' (aka 'long') but the argument has type 'int64_t' (aka 'long long') [-Werror,-Wformat]
                    r2->t_window, r2->r_window);
                                  ^~~~~~~~~~~~
http2/cache_http2_panic.c:117:25: error: format specifies type 'uintmax_t' (aka 'unsigned long') but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
                            r2->rxbuf->size, r2->rxbuf->tail, r2->rxbuf->head);
                                             ^~~~~~~~~~~~~~~
http2/cache_http2_panic.c:117:42: error: format specifies type 'uintmax_t' (aka 'unsigned long') but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
                            r2->rxbuf->size, r2->rxbuf->tail, r2->rxbuf->head);
                                                              ^~~~~~~~~~~~~~~
4 errors generated.
```

I realize the paradox of `intmax_t` appearing to be smaller than `int64_t` here, but apparently this is not an uncommon issue on macos. The most common suggestion is not to feed anything to a `%j` unless you know it to specifically be an `intmax_t`.

**Comment by catap** [comment]
@risicle feel free to use my patch to fix build on macOS ;) The path: https://github.com/varnishcache/varnish-cache/pull/3700

**Comment by risicle** [comment]
Success for me, macos 10.15. Thanks, @catap !
