### ISSUE TITLE
Protected headers are not readable

### ISSUE THREAD

**Issue by rocketeerbkw** [varnishcache/varnish-cache#3984]
### Expected Behavior

Protected headers values (e.g., `content-length`, and `transfer-encoding`) can be read/compared in VCL.

### Current Behavior

Attempting to access a header throws an error:

```
if (beresp.http.Content-Length ~ "[0-9]{8,}") {
```

```
Error:
Message from VCC-compiler:
('/etc/varnish/default.vcl' Line 59 Pos 7) -- (Pos 12)
  if (beresp.http.Content-Length ~ "[0-9]{8,}") {
------######-------------------------------------

Not available in subroutine 'vcl_backend_response'.
Running VCC-compiler failed, exited with 2
VCL compilation failed
```

### Steps to Reproduce (for bugs)

A minimal `default.vcl` could be

```
vcl 4.1;

sub vcl_backend_response {
  if (req.http.content-length) {
  }

  if (req.http.transfer-encoding) {
  }

  if (beresp.http.content-length) {
  }

  if (beresp.http.transfer-encoding) {
  }
}

```

All of these `if` statements will throw the same error `Not available in subroutine 'vcl_backend_response'.`. Attempting to compare the header to a value using `~` or `==` also throw the same error.

We have a failing example in https://github.com/uselagoon/lagoon-images/pull/830.

### Context

This broke in our automated tests on an upgrade from 7.3 to 7.4. We have a [`default.vcl` that does a check](https://github.com/uselagoon/lagoon-images/blob/main/images/varnish/default.vcl#L52-L66) on size of the request by reading `content-length`.

The release notes for 7.4 and documentation call out that `content-length` is now a protected header which can't be set or unset. But the docs also explicitly say it can still be read, but that appears to not be the case? I assume this is the relevant PR https://github.com/varnishcache/varnish-cache/pull/3810.

From the [docs](https://varnish-cache.org/docs/7.4/reference/vcl-var.html#protected-headers) (emphasis mine):

>  The `content-length` and `transfer-encoding` headers are **read-only**.

### Varnish Cache version

arnishd (varnish-7.4.0 revision f07a6d615c054cf73c9250f3f09d063ac344dff2)

### Operating system

alpine 3.15.10

### Source of binary packages used (if any)

docker varnish:7.4-alpine

**Comment by Dridi** [comment]
Wow, this one went unnoticed:

```
       beresp.http.content-length
          Type: HEADER

          Readable from: client

          The content-length header field is protected, see protected_headers.

       beresp.http.transfer-encoding
          Type: HEADER

          Readable from: client

          The transfer-encoding header field is protected, see protected_headers.
```

It should say readable from backend.

**Comment by tobybellwood** [comment]
ooh - thanks @Dridi - I guess the bereq.x and resp.x ones need fixing too?

**Comment by notr1ch** [comment]
This seems like more than just a documentation issue given that the VCL compilation fails. Or is it intended that protected headers can't even be read?

**Comment by simonvik** [comment]
Varnish 7.4.1 just got released and should solve this issue, `doc/sphinx/reference/vcl_var.rst` is being parsed and is not just documentation.

**Comment by notr1ch** [comment]
😱

**Comment by Dridi** [comment]
The documentation is authoritative and structured, we derive the effective scope of variables from it.

**Comment by notr1ch** [comment]
Got it, I just wanted to be sure that this issue was fixed before I upgraded to 7.4. From an external view, I certainly didn't expect commits modifying documentation to affect program behavior.

**Comment by rocketeerbkw** [comment]
Confirmed 7.4.1 fixes it, thanks!

@Dridi I believe there is a mistype in [the new tests](https://github.com/varnishcache/varnish-cache/commit/21f8d0456e9551309bb51469e2846930ea646ecc), shouldn't `content-encoding` be `transfer-encoding`?

**Comment by Dridi** [comment]
It seems I have a serious copy-pasta problem.
